---
sidebar: sidebar 
permalink: automation/automation-introduction.html 
summary: La automatización de las soluciones de NetApp permite al cliente automatizar la implementación, la configuración y la ejecución de muchas tareas comunes de aplicaciones e infraestructura. 
keywords: netapp, solutions, automation, ansible, terraform 
---
= Automatización de soluciones de NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La automatización de las soluciones de NetApp permite al cliente automatizar la implementación, la configuración y la ejecución de muchas tareas comunes de aplicaciones e infraestructura.



== Introducción

Al brindar soluciones para enfrentar los desafíos comerciales actuales, NetApp ofrece soluciones con los siguientes objetivos:

* Proporcionar pasos de implementación y configuración validados,
* Proporcionar soluciones que sean fácilmente consumibles,
* Proporcionar una implementación de solución que tenga un resultado predecible, sea fácil de repetir y escalable en toda la empresa del cliente.


Para lograr estos objetivos, es fundamental que la implementación y configuración de la infraestructura y/o aplicaciones entregadas a través de nuestras soluciones se simplifique mediante la automatización.  NetApp se compromete a simplificar el consumo de soluciones a través de la automatización.

Al utilizar herramientas de automatización de código abierto como Red Hat Ansible, HashiCorp Terraform o Microsoft Powershell, las soluciones de NetApp tienen la capacidad de automatizar la implementación de aplicaciones, el aprovisionamiento de la nube, la gestión de la configuración y muchas otras tareas de TI comunes.  Las soluciones de NetApp aprovechan los artefactos de automatización disponibles públicamente, además de proporcionar automatización creada por NetApp , para simplificar la implementación general de una solución.

Cuando haya capacidades de automatización disponibles, el material complementario de la solución guiará al usuario a través del proceso para automatizar la solución o los pasos de la solución a través de las herramientas de automatización específicas.
